### ISSUE TITLE
Youtube videos stop loading after the first few seconds

### ISSUE THREAD

**Issue by rfrelow** [WebMemex/webmemex-extension#120]
If "Store every visited webpage" is enabled, no youtube videos load after the first few seconds. Disabling this feature and refreshing fixes the problem.

I'm using Webmemex 0.2.2, found here:

https://blog.webmemex.org/2017/07/10/keep-all-the-gems/

**Comment by Treora** [comment]
Thanks for reporting. I suspect this has the same cause as similar problems I recently discovered: The freeze-dry code adds a CSP (that prohibits networking connections) to the page's snapshot, but Firefox erroneously applies this also to the currently viewed page itself.

We might have to create a workaround while this bug exists, or perhaps we won't encounter this problem anymore after making other planned changes to freeze-dry (I'm thinking about running most of the freeze-dry code in the background process instead of the content script).

This underlying issue is tracked in [freeze-dry #10](https://github.com/WebMemex/freeze-dry/issues/10), and is reported to Mozilla [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1382869).

**Comment by Treora** [comment]
Underlying issue is fixed in Firefox 57, I just checked it in Nightly and it seems to work. Closing this.
