### ISSUE TITLE
Keep <noscript> when appropriate (was: Images not in snapshots from Medium.com)

### ISSUE THREAD

**Issue by dvn0** [WebMemex/webmemex-extension#134]
Images in articles from Medium are not showing up in my snapshots. 

[This page for example.](https://medium.com/we-distribute/blushy-crushy-fediverse-idol-a-chat-with-lain-about-pleroma-4ff578b99752) 

**To reproduce:**
1.  noscript extension on, blocking all JS.
2. Snapshot the [page](https://medium.com/we-distribute/blushy-crushy-fediverse-idol-a-chat-with-lain-about-pleroma-4ff578b99752) with WebMemex

**Comment by Treora** [comment]
Thanks for reporting; there seem to be more issues with images, which I have not yet understood. I am currently rewriting [freeze-dry](https://github.com/WebMemex/freeze-dry), the code that does the snapshotting, so I will try to fix this issue there.

**Comment by Treora** [comment]
Not sure why I did not realise this before: Medium.com lazily loads each image using javascript, and also adds the image in a `<noscript>` tag to show it when scripts are disabled. But freeze-dry removes all `<noscript>` tags, under the assumption that scripts have been executed, e.g. in order to not to end up with both images in this case. So the solution is to keep `<noscript>` tags, and perhaps convert them into `<div>` tags, when the page was viewed with javascript disabled. See the corresponding [comment in freeze-dry](https://github.com/WebMemex/freeze-dry/blob/eb356526fbe38b9eec0fe74d0954a80edc19183d/src/make-dom-static/index.js#L12-L17):

    // If noscript content was not shown, we do not want it to show in the snapshot either. Also, we
    // capture pages after scripts executed (presumably), so noscript content is likely undesired.
    // TODO We should know whether noscript content was visible, and if so keep it in the doc.
    // TODO Keep noscript content in fetched iframe docs, as scripts have not been executed there?
    const noscripts = Array.from(doc.querySelectorAll('noscript'))
    noscripts.forEach(element => element.parentNode.removeChild(element))

Good to have a real-world use case for this now.

**Comment by Treora** [comment]
I suppose it makes sense to move this issue to the freeze-dry repo: [#32 there](https://github.com/WebMemex/freeze-dry/issues/32).
