### ISSUE TITLE
Settings dashboard

### ISSUE THREAD

**Issue by Treora** [WebMemex/webmemex-extension#16]
Components:
- Editable blacklist (allowing to add/delete/edit entries) (see #20)
- Shortcut setting(s) (for now there is just one, that opens the search overview)
- Scary red button to delete all data? (or should users just uninstall the extension?)

And probably some more things will pop up.

**Comment by aquibm** [comment]
I'll be picking this one up today.

**Comment by reficul31** [comment]
I would like to assist @aquibm in this issue. According to what I understood from the issue description we need to make 3 components first one being a blacklist component, a shortcut settings component and one main component.
According to me the steps to undertake are.
1. Go over the design of the already existing settings component
2. Design the new components that fit the theme of the settings component. Get it approved.
3. Add the UI/UX functionality like routing.
4. Make the components.
5. Document clearly for future devs so that the back end can be plugged in easily

Please tell correct me if I misunderstood. I would really like to assist @aquibm in this task.

**Comment by Rohanhacker** [comment]
Can I work on this ?

**Comment by blackforestboi** [comment]
@Rohanhacker You have to talk to @aquibm, as he has already taken it on and is almost finished with the blacklist function. 
There might be an option to help on the short-cut functionality.

**Comment by Rohanhacker** [comment]
@aquibm is there an option to help on the short-cut functionality ?

**Comment by Treora** [comment]
Basic framework is there, blacklist is being worked on (#20), other aspects can be handled in new&separate issues. Closing this one.
