### ISSUE TITLE
Make full-page snapshot

### ISSUE THREAD

**Issue by blackforestboi** [WebMemex/webmemex-extension#37]
## Goal of module: 
Make a complete screenshot of a page

**Comment by Treora** [comment]
This was something I put up as a plan, and thought would be easy to do, but it turns out it may not really be feasible. I had looked at [mozilla pageshot](https://github.com/mozilla-services/pageshot) which just [used](https://github.com/mozilla-services/pageshot/blob/43e3e44467f36c1421e0f5ed3358130ea7115aa4/addon/data/framescripts/screenshot.js#L69) [Canvas.drawWindow](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawWindow), but apparently that was not a standard API or anything we can use, and [according to themselves](https://github.com/mozilla-services/pageshot/issues/2178) there is no good alternative.

Therefore, I am closing this issue again. We can think about using `tabs.captureVisibleTab` in more creative ways (stitching snapshots?), but it does not seem worth it for now.
