### ISSUE TITLE
Log viewed (scrolled) part of page.

### ISSUE THREAD

**Issue by Treora** [WebMemex/webmemex-extension#44]
A common feature request is to have the extension keep track not just of which pages have been viewed, but also which part of those pages. For this we could make a possibly indepedent module, that listens to scrolling events and creates a map of the parts of the page that have been looked at.

A first implementation could just tell which ranges of the full document height have been visible at some moment. Or it could even just give (assuming one started at the top) a percentage, indicating down to which place the page has been visible: 100% means one scrolled all the way down.

An improved version of this code would filter out quick scrolls, to log only areas that one actually spent time looking at.

For long writings (the primary purpose of this feature) this may work quite acceptably, though another big improvement would be to take into account that document layout depends on e.g. screen size. It would therefore be good to somehow log *what* one has viewed, e.g. which sections or exactly which text of the document.

First things first though. Let's start with a script that reports the scrolled area compared to the whole document height. If anyone has a good idea (or existing code) for how to approach this, feel free to share.

**Comment by RohanMishra97** [comment]
One idea to find Scroll-able area by taking the difference between the Document Height and the Browser's current height(to be changed in resize events) and taking ratio of the scrollTop to the Scroll-able area.
In order to deal with the cost of  onScroll function - a setInterval method could be used.

**Comment by colsondonohue** [comment]
In order to filter out quick scrolls, you could [debounce](https://davidwalsh.name/javascript-debounce-function) the function being called when onScroll fires. This will prevent the function from firing until the rate of scrolling has slowed down/stopped, depending on the wait time chosen. 

I'm envisioning something where, on hovering over each card, the card expands such that the small screenshot becomes a full map of the page with the viewed parts highlighted a different colour. In order to do so, we'd need to log the start and end vertical offsets of each section of the page that was looked at.

**Comment by Treora** [comment]
> In order to filter out quick scrolls, you could debounce the function being called when onScroll fires

Something like that seems right indeed. Possibly @RohanMishra97 had a point though:
> In order to deal with the cost of onScroll function - a setInterval method could be used.

The same idea of debouncing or some kind of filtering could still be used of course. May need a bit of testing to find out what works nicely, or some research to see if somebody tackled this problem already.

**Comment by blackforestboi** [comment]
> or some research to see if somebody tackled this problem already.

I just found this: https://github.com/williamngan/roll

They also have a nice demo: http://williamngan.github.io/roll/demo/index.html

**Comment by shreyabhat98** [comment]
I am a newcomer. I would like to work on this if no one's working on it.

**Comment by blackforestboi** [comment]
Hey @shreyabhat98 

Thanks for your kind offer in taking this on. We had a lot of interested people recently, so before starting, I'd invite you to complete the short onboarding survey.
This helps us to keep tabs of everyone involved and know which skills are present. 

Also in this survey you find information regarding how to join our slack channel etc. 

Here is the survey: [worldbrain.io/onboarding](http://worldbrain.io/onboarding) 

Thanks a lot!

**Comment by shreyabhat98** [comment]
Can I start working on the issue now?

**Comment by blackforestboi** [comment]
Hello @shreyabhat98 

Have you done the onboarding survey, because I can't see your name on it?

Another reason for this survey is to gauge how much experience people have. Unfortunately we are currently not equipped with enough (wo)man-power to help beginners to learn JS or React. 
So we expect proficiency with one or both of them.

This is because it takes quite a lot of time to do PR-reviews for beginner code. And as much as we like to provide a good learning environment also for beginners, we currently just can't. 

Judging from your GitHub profile it seems as that you are fairly new to (open-source) software development.
If that is true, it is not a good idea to take on this task. 

It may be best to first study more by yourself and work on smaller projects, to get proficient with node ecosystem, ES6, React, Redux.

I am really sorry.
Oliver

**Comment by reficul31** [comment]
@Treora @oliversauter How about in addition to logging the scrolled part of the page, when the user revisits the page we give him a choice to scroll back to the position where he left off? This would come in handy in many online blogs as people(especially me) might forget how much of the document they are through reading.

**Comment by bohrium272** [comment]
@Treora if the exact scroll position is known, would it help with creating precise links( #77 ) of a page?

**Comment by Treora** [comment]
@reficul31: scrolling to where you left off by default may be a nice idea indeed. At least for pages in our personal web this would be easy to do, as they are static. On the live web, doing this per URL may be annoying on changing websites (e.g. your newspaper frontpage), but doing it for the specific page version (determined by deduplication) may be fine.

@arpitgogia: Scroll position is to screen-dependent to use in a link, if that is what you mean. The other way around, however, when following a precise link, one can scroll to the fragment that was linked to (like [this page](https://blog.webmemex.org/2017/04/24/progress-update/#%22creating%20and%20owning%20your%20personal%20piece%20of%20web%22) does it).

In line with the message of that linked post however, it may be good to consider this issue something to add later on. At least we should first get #91 done.

**Comment by Treora** [comment]
Closing this issue; features like this one have been fading off the roadmap for a while. Maybe some day..
