### ISSUE TITLE
Export zip file with all the things!

### ISSUE THREAD

**Issue by janpaul123** [WebMemex/webmemex-extension#99]
To have a backup if my laptop dies. 💻 🔥

**Comment by Treora** [comment]
Valid concern indeed. A reasonbly quick solution would be to [dump](https://github.com/pouchdb-community/pouchdb-replication-stream) and [load](https://github.com/pouchdb-community/pouchdb-load) the database contents. Syncing data to a server is already on the road map, and would provide another solution.

By the way, rather than dumping/syncing the database as one opaque object, I intend the data to be written to and read from a more interoperable format, to not make it exclusive to this application. At least the stored pages and notes could be html files. Metadata could perhaps be stored as linked data, I am thinking of building on [LDP](https://www.w3.org/TR/ldp-primer/).

**Comment by bnvk** [comment]
According to @treora the code at `HEAD` has a command that does not dump the whole database (metadata etc), but does download all snapshots which is accessible by running in Overview JS console:

```
downloadAllPages().
```

Alternatively, as a crude backup of the extensions raw data, you can copy the following in Firefox 

```
cp -r ~/.mozilla/firefox/xxxxxxx.default/storage/default/moz-extension+++000000-0000-0000-0000-000000/* backup/path/memex
```

**Comment by Treora** [comment]
In v0.3.2, I finally added a button to store all your snapshots. Not as a zip, but in a folder (currently named 'Webmemex snapshots dump yyyy-mm-dd') inside your downloads folder, which seems equivalent (or better) in my view. The button just invokes the `downloadAllPages` function mentioned above.

Closing this issue, although much could be improved still. For example, there is no way to download only the snapshots made since the last time you ran such an export, there is no way to name the folder, clicking the button twice could be smarter, etc.

Rather than improving this export however, I am considering the idea to use the downloads folder as the primary/only storage location of snapshots, which could make an export feature altogether unnecessary. See issue #138.
